name: SonarCloud
on:
  push:
    branches:
      - main
      - front
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build_backend:
    name: Build and analyze backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze backend
        working-directory: ./BackEnd/gestionnotas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=danielloaizan01_code-factory \
          -Dsonar.organization=danielloaizan01 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -DskipTests=true

  build_frontend:
    name: Build and analyze frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Build and analyze frontend
        working-directory: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm run build
          sonar-scanner \
          -Dsonar.projectKey=danielloaizan01_code-factory-frontend \
          -Dsonar.organization=danielloaizan01 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=. \
          -Dsonar.exclusions=**/__tests__/**/*,**/*.test.js,**/*.spec.js \
          -Dsonar.javascript.file.suffixes=.js,.jsx \
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \
          -X
